name: Tests
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: docker build -t test.meow.meow -f tests/Dockerfile .
    - name: Test
      run: docker run test.meow.meow
